FROM openshift/origin-release:golang-1.10
COPY . /go/src/github.com/kubernetes-csi/livenessprobe/
RUN cd /go/src/github.com/kubernetes-csi/livenessprobe/ && \
    go build -o livenessprobe ./cmd

FROM centos:7

COPY --from=0 /go/src/github.com/kubernetes-csi/livenessprobe/livenessprobe /usr/bin/

RUN useradd livenessprobe
USER livenessprobe

ENTRYPOINT ["/usr/bin/livenessprobe"]
