FROM registry.svc.ci.openshift.org/ocp/builder:golang-1.10 AS builder
WORKDIR /go/src/github.com/kubernetes-csi/livenessprobe
COPY . .
RUN go build -o livenessprobe ./cmd

FROM registry.svc.ci.openshift.org/ocp/4.0:base
COPY --from=builder /go/src/github.com/kubernetes-csi/livenessprobe/livenessprobe /usr/bin/
RUN useradd livenessprobe
USER livenessprobe
ENTRYPOINT ["/usr/bin/livenessprobe"]
